# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('app_ref_no', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_code', models.CharField(default='+91', max_length=20)),
                ('resume', models.FileField(upload_to='')),
                ('skills', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Applied', max_length=255)),
                ('status_changed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Applications',
                'verbose_name': 'Application',
                'db_table': 'applications',
            },
        ),
    ]
